### ISSUE TITLE
tabular data/ noisy instances 

### ISSUE THREAD

**Issue by nazaretl** [ragavsachdeva/EvidentialMix#1]
Hi,
thanks for sharing your implementation. I have two questions about it:

1.	Does it also work on tabular data?
2.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set).

Thanks!

**Comment by ragavsachdeva** [comment]
Hi, apologies for the delayed response. 

1. We didn't experiment with tabular data so I can't really comment on it. It's an interesting question though.
2. It's been a while since I have looked at this code but you should be able to get the noisy instances from [this code line](https://github.com/ragavsachdeva/EvidentialMix/blob/main/Train_cifar.py#L460).

Hope this helps.
